[project]
name = "anonymacy"
version = "0.0.2"
description = "anonymaCy is a spaCy extension for anonymizing PII using rule-based recognizers, context-aware processing, conflict resolution and customizable anonymization."
readme = "README.md"
authors = [
    { name = "viclang", email = "viclang.github@pm.me" }
]
requires-python = ">=3.12"
dependencies = [
    "spacy>=3.8.7",
    "phonenumbers>=9.0.8",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/anonymacy"]
