[project]
name = "anonymacy"
version = "0.0.3"
description = "anonymaCy is a spaCy extension for anonymizing PII using rule-based recognizers, context-aware processing, conflict resolution and customizable anonymization."
readme = "README.md"
authors = [
    { name = "viclang", email = "viclang.github@pm.me" }
]
requires-python = ">=3.9,<3.14"
dependencies = [
    "spacy>=3.8.7",
]

[dependency-groups]
dev = [
    "marimo",
    "pytest",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/anonymacy"]
