[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "anonymacy"
version = "0.0.7"
requires-python = ">=3.9,<3.14"
dependencies = ["spacy>=3.8.7"]

[tool.hatch.build.targets.wheel]
packages = ["src/anonymacy"]

[project.entry-points.spacy_factories]
recognizer = "anonymacy.recognizer:Recognizer"
context_enhancer = "anonymacy.context_enhancer:ContextEnhancer"
conflict_resolver = "anonymacy.conflict_resolver:ConflictResolver"
anonymizer = "anonymacy.anonymizer:Anonymizer"

[dependency-groups]
dev = [
    "marimo",
    "pytest",
]

[tool.hatch.metadata]
allow-direct-references = true